"""
Created on Sun Oct 29 10:05:00 2023

@author: Erin Richardson
"""

from textaugment import EDA
import random

# Copy data from cleaned dataframe into a new one for sentences to be augmented
# the 'clean' dataframe is generated by cleaning_and_eda.py
augmented = clean[['clean', 'emotion']].copy()

# Initialize EDA (Easy Data Augmentation) object
eda = EDA()

# Iterate through the rows of the original dataframe and replace the text with augmented text

for index, row in augmented.iterrows():
    text = row['clean']
    emotion = row['emotion']
    
    # Perform data augmentation - synonym replacement
    augmented_texts = eda.synonym_replacement(text)
    
    # Replace the original text with augmented text
    if augmented_texts:
        augmented.at[index, 'clean'] = augmented_texts
    
# Now, the 'clean' DataFrame contains augmented text samples in place of the original text